import {MD3LightTheme, configureFonts} from 'react-native-paper'
import type {MD3Theme} from 'react-native-paper'

const fontConfig = {
	displayLarge: {
		fontFamily: 'System',
		fontSize: 57,
		fontWeight: '400' as const,
		letterSpacing: 0,
		lineHeight: 64,
	},
	displayMedium: {
		fontFamily: 'System',
		fontSize: 45,
		fontWeight: '400' as const,
		letterSpacing: 0,
		lineHeight: 52,
	},
	displaySmall: {
		fontFamily: 'System',
		fontSize: 36,
		fontWeight: '400' as const,
		letterSpacing: 0,
		lineHeight: 44,
	},
	headlineLarge: {
		fontFamily: 'System',
		fontSize: 32,
		fontWeight: '400' as const,
		letterSpacing: 0,
		lineHeight: 40,
	},
	headlineMedium: {
		fontFamily: 'System',
		fontSize: 28,
		fontWeight: '400' as const,
		letterSpacing: 0,
		lineHeight: 36,
	},
	headlineSmall: {
		fontFamily: 'System',
		fontSize: 24,
		fontWeight: '400' as const,
		letterSpacing: 0,
		lineHeight: 32,
	},
	titleLarge: {
		fontFamily: 'System',
		fontSize: 22,
		fontWeight: '400' as const,
		letterSpacing: 0,
		lineHeight: 28,
	},
	titleMedium: {
		fontFamily: 'System',
		fontSize: 16,
		fontWeight: '500' as const,
		letterSpacing: 0.15,
		lineHeight: 24,
	},
	titleSmall: {
		fontFamily: 'System',
		fontSize: 14,
		fontWeight: '500' as const,
		letterSpacing: 0.1,
		lineHeight: 20,
	},
	bodyLarge: {
		fontFamily: 'System',
		fontSize: 16,
		fontWeight: '400' as const,
		letterSpacing: 0.5,
		lineHeight: 24,
	},
	bodyMedium: {
		fontFamily: 'System',
		fontSize: 14,
		fontWeight: '400' as const,
		letterSpacing: 0.25,
		lineHeight: 20,
	},
	bodySmall: {
		fontFamily: 'System',
		fontSize: 12,
		fontWeight: '400' as const,
		letterSpacing: 0.4,
		lineHeight: 16,
	},
	labelLarge: {
		fontFamily: 'System',
		fontSize: 14,
		fontWeight: '500' as const,
		letterSpacing: 0.1,
		lineHeight: 20,
	},
	labelMedium: {
		fontFamily: 'System',
		fontSize: 12,
		fontWeight: '500' as const,
		letterSpacing: 0.5,
		lineHeight: 16,
	},
	labelSmall: {
		fontFamily: 'System',
		fontSize: 11,
		fontWeight: '500' as const,
		letterSpacing: 0.5,
		lineHeight: 16,
	},
}

export const lightTheme: MD3Theme = {
	...MD3LightTheme,
	dark: false,
	fonts: configureFonts({config: fontConfig}),
	colors: {
		...MD3LightTheme.colors,
		primary: '#5B6BFF',
		primaryContainer: 'rgba(91, 107, 255, 0.12)',
		secondary: '#3DD7E5',
		secondaryContainer: 'rgba(61, 215, 229, 0.14)',
		tertiary: '#F5D547',
		tertiaryContainer: 'rgba(245, 213, 71, 0.14)',
		surface: '#FFFFFF',
		surfaceVariant: '#F5F5F5',
		surfaceDisabled: 'rgba(255, 255, 255, 0.38)',
		background: '#F8F9FA',
		error: '#FF3A5C',
		errorContainer: 'rgba(255, 58, 92, 0.14)',
		onPrimary: '#FFFFFF',
		onPrimaryContainer: '#4A59E6',
		onSecondary: '#0A0B0F',
		onSecondaryContainer: '#2BB8C4',
		onTertiary: '#0A0B0F',
		onTertiaryContainer: '#D4B83E',
		onSurface: '#1F2937',
		onSurfaceVariant: '#6B7280',
		onSurfaceDisabled: 'rgba(31, 41, 55, 0.38)',
		onError: '#FFFFFF',
		onErrorContainer: '#FF3A5C',
		onBackground: '#1F2937',
		outline: '#E1E4E8',
		outlineVariant: '#D1D5DA',
		inverseSurface: '#1F2937',
		inverseOnSurface: '#F8F9FA',
		inversePrimary: '#7886FF',
		shadow: '#000000',
		scrim: '#000000',
		backdrop: 'rgba(248, 249, 250, 0.72)',
		elevation: {
			level0: 'transparent',
			level1: '#FFFFFF',
			level2: '#F8F9FA',
			level3: '#F5F5F5',
			level4: '#EEEEEE',
			level5: '#E8E8E8',
		},
	},
	roundness: 10,
}

export const lightColors = {
	background: '#F8F9FA',
	surface: '#FFFFFF',
	elevated: '#F5F5F5',
	border: '#E1E4E8',
	borderStrong: '#D1D5DA',
	onSurface: '#1F2937',
	onSurfaceMuted: '#6B7280',
	onSurfaceFaint: '#9CA3AF',
	primary: '#5B6BFF',
	primaryHover: '#7886FF',
	primaryPressed: '#4A59E6',
	secondary: '#3DD7E5',
	tertiary: '#F5D547',
	success: '#2BE08C',
	warning: '#F5D547',
	info: '#3DD7E5',
	error: '#FF3A5C',
	focus: 'rgba(91, 107, 255, 0.35)',
}
